services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: virtualmechanic-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: virtualmechanic-frontend
    ports:
      - "3000:3000"
    
    command:  npm run dev -- --port 3000 --host
