version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
      - CORS_ORIGINS=http://localhost:3000
    volumes:
      - ./backend/app:/app/app
      - ./data:/app/data:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 2s
      retries: 10

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE=http://localhost:8000
    depends_on:
      backend:
        condition: service_healthy

